version: '3.7'

services:
  eth:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    env_file: .env
    environment:
      NODE_PORT: 5000
      INFURA_API_KEY: ${INFURA_API_KEY}
    ports:
      - '5000:5000'
    command: yarn dev